### ISSUE TITLE
Mashallah Great app

### ISSUE THREAD

**Issue by fawazahmed0** [mr-islam/layl-pwa#65]
Salam,

I didn't know there was something as layl.app . I thought no website/app existed to calculate tahajjud times. 
I ended up creating a basic site to calculate tahajjud times for myself. 
God bless you for your work.

You can refer the [site](https://fawazahmed0.github.io/last-third-night-calculator/) and [code](https://github.com/fawazahmed0/last-third-night-calculator) , maybe it might help you to make your website better.

Jazakallah

**Comment by mr-islam** [comment]
Wa alaykum as salam,

Ameen, wa iyyakum may Allah accept and bless us all

Alhamdulillah, Layl was able to help :)

I'll take a look at you site inshaAllah, it's always amazing to hear from other Muslims and look at their code

You are most welcome to contribute to Layl as well ;) — I'm sorry for any bad code styles, but alhamdulillah it works

**Comment by fawazahmed0** [comment]
Oh, I forgot to inform you that I have few api's and apps that you might find helpful, here is the link:
https://fawazahmed0.github.io/islamic-project

**Comment by mr-islam** [comment]
How are you doing brother? Alhamdulillah Layl has gotten some awesome contributions recently. I'll close this issue
