### ISSUE TITLE
Fix weird dependency errors

### ISSUE THREAD

**Issue by mr-islam** [mr-islam/layl-pwa#68]
Can't even run dev or watch scripts, seems like some dependency?

**Comment by Mhdtarek** [comment]
I would honestly consider the entire project be moved to vite, Yes it may be hard but it will pay off

**Comment by mr-islam** [comment]
Yes... seems like the best option. I just want to restart in Sveltekit, most components and logic can be copy-pasted without hassle inshaAllah.

Right now I'm finishing things up for the release of [markaz](https://github.com/sufone/markaz) and [mubeen](https://github.com/sufone/mubeen-v2), so at least till then Layl is on the backburner. Maybe in the summer I'll have time for it... Unless you'd like to fork and make the transition :)

**Comment by Mhdtarek** [comment]
I have begun work on the Vite transition I will see how everything will do, I have tried svelte-kit but it un needed for SSR and routing so I have gone for Vite with Svelte

**Comment by mr-islam** [comment]
That is so amazing! May Allah reward you greatly!! 💚

Vite should be fine, like you said no need for SSR, since Layl is an SPA. Please do let me know if I can help with anything, like understanding my (bad) code, implementation ideas, etc. 

Starting with a Vite with Svelte starter should be cleanest, so please feel free to copy all the code from here that is usable. All the code is licensed in `AGPL v3`.

**Most important**: using the same calculation logic and script, since this code has been tried and tested around the world, for 3+ years with no problems that I know of, alhamdulillah. Most views and UI can also be copied over I think and then built upon.

Feel free to ask anything so that we make the best decision from the start, and all time/energy is spent efficiently :)

**Comment by mr-islam** [comment]
Alhamdulillah I updated the repo to deploy from cloudflare pages, and updated the DNS settings to reflect, now the latest version is live! 

https://layl.app. 

Might take a few hours to update for everyone, let DNS updates propogate, etc. It's already showing up for me.

Jazakumullahu khayran brother @Mhdtarek, you were a huge help and InshaAllah you will get the reward of everyone who benefits from Layl (right now 800+ visitors weekly!)

Please do join the Sufone discord (https://discord.gg/p9MFQdES), everyone is welcome, it's a brand new server and should be easier to plan and discuss over there. 

We'll always try to bring final plans and post them on GitHub after discussions so it's publicly available.
